import { spawn } from 'node:child_process'
import {
  createWriteStream, existsSync, mkdirSync, readdirSync, readFileSync,
  renameSync, rmSync, statSync, writeFileSync,
} from 'node:fs'
import { createServer } from 'node:net'
import { homedir } from 'node:os'
import { join } from 'node:path'

const OWNER_REPO = 'router-for-me/CLIProxyAPI'
const FALLBACK_VERSION = '7.2.131'
const HEALTH_INTERVAL_MS = 20_000
const HEALTH_TIMEOUT_MS = 4_000
const MAX_BACKOFF_MS = 60_000
const LOG_ROTATE_BYTES = 5 * 1024 * 1024

export function proxyHome() {
  if (process.env.DSH_CLIPROXY_HOME) return process.env.DSH_CLIPROXY_HOME
  const dshHome = process.env.DSH_HOME || join(homedir(), '.dsh')
  return join(dshHome, 'cliproxy')
}

function assetFor(version) {
  const os = process.platform === 'win32' ? 'windows' : process.platform === 'darwin' ? 'darwin' : 'linux'
  const arch = process.arch === 'arm64' ? 'aarch64' : 'amd64'
  const ext = os === 'windows' ? 'zip' : 'tar.gz'
  return `CLIProxyAPI_${version}_${os}_${arch}.${ext}`
}

async function fetchJson(url, timeoutMs = 10_000) {
  const response = await fetch(url, {
    headers: { 'user-agent': 'dsh-cpa-plus', accept: 'application/vnd.github+json' },
    signal: AbortSignal.timeout(timeoutMs),
  })
  if (!response.ok) throw new Error(`GET ${url} -> ${response.status}`)
  return await response.json()
}

function findExecutable(dir) {
  const queue = [dir]
  const candidates = []
  while (queue.length > 0) {
    const current = queue.shift()
    for (const name of readdirSync(current)) {
      const full = join(current, name)
      const stats = statSync(full)
      if (stats.isDirectory()) {
        queue.push(full)
        continue
      }
      if (process.platform === 'win32') {
        if (name.toLowerCase().endsWith('.exe')) candidates.push({ full, size: stats.size })
      } else if (/^(cli-?proxy-?api|CLIProxyAPI)$/i.test(name)) {
        candidates.push({ full, size: stats.size })
      }
    }
  }
  candidates.sort((a, b) => b.size - a.size)
  return candidates[0]?.full
}

function run(command, args, timeoutMs = 120_000) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: 'ignore', windowsHide: true })
    const timer = setTimeout(() => {
      child.kill()
      reject(new Error(`${command} timed out`))
    }, timeoutMs)
    child.once('error', (error) => {
      clearTimeout(timer)
      reject(error)
    })
    child.once('exit', (code) => {
      clearTimeout(timer)
      if (code === 0) resolve()
      else reject(new Error(`${command} exited with ${code}`))
    })
  })
}

function pidAlive(pid) {
  if (!pid) return false
  try {
    process.kill(pid, 0)
    return true
  } catch (error) {
    return error?.code === 'EPERM'
  }
}

async function killPid(pid) {
  if (!pid) return
  try {
    if (process.platform === 'win32') {
      await run('taskkill', ['/PID', String(pid), '/T', '/F'], 15_000).catch(() => {})
    } else {
      process.kill(pid, 'SIGTERM')
      for (let waited = 0; waited < 5_000 && pidAlive(pid); waited += 200) {
        await new Promise((resolve) => setTimeout(resolve, 200))
      }
      if (pidAlive(pid)) process.kill(pid, 'SIGKILL')
    }
  } catch {
    // Already gone.
  }
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'))
  } catch {
    return undefined
  }
}

// Windows reserves whole port ranges (WinNAT/Hyper-V); binding inside one
// fails with "access permissions" even though nothing listens there.
function canBind(port) {
  return new Promise((resolve) => {
    const probe = createServer()
    probe.unref()
    probe.once('error', () => resolve(false))
    probe.listen({ host: '127.0.0.1', port }, () => {
      probe.close(() => resolve(true))
    })
  })
}

function freePort() {
  return new Promise((resolve, reject) => {
    const probe = createServer()
    probe.unref()
    probe.once('error', reject)
    probe.listen({ host: '127.0.0.1', port: 0 }, () => {
      const { port } = probe.address()
      probe.close(() => resolve(port))
    })
  })
}

function yamlQuote(value) {
  return JSON.stringify(String(value))
}

function renderConfig({ port, authDir, apiKey }) {
  return [
    '# Generated by dsh-cpa-plus (managed mode).',
    '# Manual edits to managed keys (host/port/auth-dir/api-keys) are overwritten;',
    '# everything else you add here or via the Management API is preserved as long',
    '# as the managed keys do not change.',
    'host: "127.0.0.1"',
    `port: ${port}`,
    `auth-dir: ${yamlQuote(authDir)}`,
    'api-keys:',
    `  - ${yamlQuote(apiKey)}`,
    'remote-management:',
    '  allow-remote: false',
    '  secret-key: ""',
    'logging-to-file: false',
    'usage-statistics-enabled: false',
    'request-retry: 3',
    'codex:',
    '  disable-codex-cloaking: true',
    '',
  ].join('\n')
}

export function createProxySupervisor({ logger, getSettings, getSecrets }) {
  const home = proxyHome()
  const paths = {
    home,
    bin: join(home, 'bin'),
    auth: join(home, 'auth'),
    logs: join(home, 'logs'),
    config: join(home, 'config.yaml'),
    configState: join(home, 'config.state.json'),
    current: join(home, 'bin', 'current.json'),
    pid: join(home, 'cliproxy.pid'),
    log: join(home, 'logs', 'cliproxy.log'),
  }

  const state = {
    phase: 'idle',
    mode: 'managed',
    version: undefined,
    exe: undefined,
    pid: undefined,
    error: undefined,
    startedAt: undefined,
    lastHealthyAt: undefined,
    // Port the managed proxy actually listens on. May differ from the
    // configured port when that one is unbindable (Windows reserved ranges).
    effectivePort: readJson(join(home, 'config.state.json'))?.effectivePort,
  }

  let child
  let stopping = false
  let restartTimer
  let healthTimer
  let backoffMs = 1_000
  let startPromise

  const log = (message) => logger?.info?.(`cliproxy: ${message}`)
  const warn = (message) => logger?.warn?.(`cliproxy: ${message}`)

  function settings() {
    return getSettings()
  }

  function baseUrl() {
    const conf = settings()
    if (conf.mode === 'external') {
      return String(conf.externalUrl || 'http://127.0.0.1:8317').replace(/\/+$/, '')
    }
    return `http://127.0.0.1:${state.effectivePort ?? conf.port ?? 8317}`
  }

  async function healthAt(url) {
    try {
      const secrets = await getSecrets()
      const response = await fetch(`${url}/v0/management/config`, {
        headers: { authorization: `Bearer ${secrets.managementKey}` },
        signal: AbortSignal.timeout(HEALTH_TIMEOUT_MS),
      })
      return response.ok
    } catch {
      return false
    }
  }

  function health() {
    return healthAt(baseUrl())
  }

  async function resolveEffectivePort(desired) {
    if (await canBind(desired)) return { port: desired }
    // Port is taken or reserved. If a proxy that knows our management key is
    // already answering there, adopt it instead of failing.
    if (await healthAt(`http://127.0.0.1:${desired}`)) return { port: desired, adopted: true }
    const prior = state.effectivePort
    if (prior && prior !== desired) {
      if (await healthAt(`http://127.0.0.1:${prior}`)) return { port: prior, adopted: true }
      if (await canBind(prior)) return { port: prior }
    }
    const picked = await freePort()
    warn(`port ${desired} is not bindable (reserved range or in use); using ${picked} instead`)
    return { port: picked }
  }

  async function resolveVersion(pin) {
    const cleaned = String(pin || 'latest').trim().replace(/^v/i, '')
    if (cleaned && cleaned !== 'latest') return cleaned
    try {
      const release = await fetchJson(`https://api.github.com/repos/${OWNER_REPO}/releases/latest`)
      const tag = String(release.tag_name || '').replace(/^v/i, '')
      if (tag) return tag
    } catch (error) {
      warn(`latest-version lookup failed: ${error instanceof Error ? error.message : error}`)
    }
    const current = readJson(paths.current)
    if (current?.version && current?.exe && existsSync(current.exe)) return current.version
    return FALLBACK_VERSION
  }

  async function download(version) {
    const asset = assetFor(version)
    const url = `https://github.com/${OWNER_REPO}/releases/download/v${version}/${asset}`
    const targetDir = join(paths.bin, version)
    const archive = join(paths.bin, asset)
    mkdirSync(targetDir, { recursive: true })
    log(`downloading ${url}`)
    const response = await fetch(url, {
      headers: { 'user-agent': 'dsh-cpa-plus' },
      signal: AbortSignal.timeout(600_000),
    })
    if (!response.ok || !response.body) throw new Error(`download failed: ${response.status} ${url}`)
    const file = createWriteStream(archive)
    await new Promise((resolve, reject) => {
      const reader = response.body.getReader()
      const pump = () => reader.read().then(({ done, value }) => {
        if (done) {
          file.end(resolve)
          return undefined
        }
        return file.write(value) ? pump() : new Promise((next) => file.once('drain', next)).then(pump)
      }).catch(reject)
      pump()
      file.once('error', reject)
    })
    // bsdtar (Windows 10+) and GNU tar both extract zip/tar.gz respectively.
    await run('tar', ['-xf', archive, '-C', targetDir])
    rmSync(archive, { force: true })
    const exe = findExecutable(targetDir)
    if (!exe) throw new Error(`no executable found inside ${asset}`)
    writeFileSync(paths.current, `${JSON.stringify({ version, exe }, null, 2)}\n`)
    return exe
  }

  async function ensureBinary() {
    const conf = settings()
    if (conf.binaryPath) {
      if (!existsSync(conf.binaryPath)) throw new Error(`binaryPath does not exist: ${conf.binaryPath}`)
      state.version = 'custom'
      return conf.binaryPath
    }
    const pinned = String(conf.version || 'latest').trim().replace(/^v/i, '')
    const current = readJson(paths.current)
    if (current?.exe && existsSync(current.exe)
      && (pinned === 'latest' || pinned === '' || current.version === pinned)) {
      state.version = current.version
      return current.exe
    }
    state.phase = 'installing'
    const version = await resolveVersion(pinned)
    const installed = readJson(paths.current)
    if (installed?.version === version && installed?.exe && existsSync(installed.exe)) {
      state.version = version
      return installed.exe
    }
    const exe = await download(version)
    state.version = version
    return exe
  }

  async function ensureConfig(port) {
    const secrets = await getSecrets()
    const desired = { port, authDir: paths.auth, apiKey: secrets.apiKey }
    const previous = readJson(paths.configState)
    const drifted = !previous
      || previous.port !== desired.port
      || previous.authDir !== desired.authDir
      || previous.apiKey !== desired.apiKey
    if (!existsSync(paths.config) || drifted) {
      if (existsSync(paths.config) && drifted) {
        warn('managed config keys changed; regenerating config.yaml (other edits are lost)')
      }
      writeFileSync(paths.config, renderConfig(desired))
    }
    writeFileSync(paths.configState, `${JSON.stringify({ ...desired, effectivePort: port }, null, 2)}\n`)
  }

  function rotateLog() {
    try {
      if (existsSync(paths.log) && statSync(paths.log).size > LOG_ROTATE_BYTES) {
        const previous = `${paths.log}.1`
        rmSync(previous, { force: true })
        renameSync(paths.log, previous)
      }
    } catch {
      // Best effort.
    }
  }

  async function spawnProxy(exe) {
    const secrets = await getSecrets()
    rotateLog()
    const out = createWriteStream(paths.log, { flags: 'a' })
    out.write(`\n----- dsh-cpa-plus spawn ${new Date().toISOString()} -----\n`)
    const proc = spawn(exe, ['--config', paths.config], {
      cwd: paths.home,
      env: { ...process.env, MANAGEMENT_PASSWORD: secrets.managementKey },
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    proc.stdout.pipe(out, { end: false })
    proc.stderr.pipe(out, { end: false })
    proc.once('exit', (code, signalName) => {
      out.end()
      if (child === proc) child = undefined
      if (state.pid === proc.pid) state.pid = undefined
      if (stopping) return
      state.phase = 'stopped'
      warn(`process exited (code=${code ?? ''} signal=${signalName ?? ''}); restarting in ${backoffMs}ms`)
      clearTimeout(restartTimer)
      restartTimer = setTimeout(() => {
        restartTimer = undefined
        start().catch((error) => warn(`restart failed: ${error instanceof Error ? error.message : error}`))
      }, backoffMs)
      backoffMs = Math.min(backoffMs * 2, MAX_BACKOFF_MS)
    })
    child = proc
    state.pid = proc.pid
    writeFileSync(paths.pid, String(proc.pid))
    return proc
  }

  async function waitHealthy(timeoutMs = 30_000) {
    const startAt = Date.now()
    while (Date.now() - startAt < timeoutMs) {
      if (await health()) return true
      if (!child && !pidAlive(state.pid)) return false
      await new Promise((resolve) => setTimeout(resolve, 800))
    }
    return false
  }

  function scheduleHealthLoop() {
    clearInterval(healthTimer)
    healthTimer = setInterval(async () => {
      if (stopping || state.phase === 'installing' || state.phase === 'starting') return
      const ok = await health()
      if (ok) {
        state.lastHealthyAt = Date.now()
        if (state.phase !== 'running' && state.mode === 'managed') state.phase = 'running'
        if (state.phase !== 'external-ok' && state.mode === 'external') state.phase = 'external-ok'
        backoffMs = 1_000
        return
      }
      if (state.mode === 'external') {
        state.phase = 'external-unreachable'
        return
      }
      const sinceHealthy = Date.now() - (state.lastHealthyAt ?? 0)
      const processGone = !child && !pidAlive(state.pid)
      if (processGone || sinceHealthy > HEALTH_INTERVAL_MS * 3) {
        warn(processGone ? 'proxy process is gone; restarting' : 'health checks failing; restarting proxy')
        await restart().catch((error) => warn(`restart failed: ${error instanceof Error ? error.message : error}`))
      }
    }, HEALTH_INTERVAL_MS)
    if (typeof healthTimer.unref === 'function') healthTimer.unref()
  }

  async function start() {
    if (startPromise) return startPromise
    startPromise = (async () => {
      stopping = false
      state.error = undefined
      const conf = settings()
      if (conf.mode !== 'managed' && conf.mode !== 'external') {
        state.mode = 'off'
        state.phase = 'off'
        return
      }
      state.mode = conf.mode === 'external' ? 'external' : 'managed'

      if (state.mode === 'external') {
        state.phase = (await health()) ? 'external-ok' : 'external-unreachable'
        scheduleHealthLoop()
        return
      }

      try {
        mkdirSync(paths.bin, { recursive: true })
        mkdirSync(paths.auth, { recursive: true })
        mkdirSync(paths.logs, { recursive: true })

        // Adopt a still-running proxy from a previous DSH process.
        const previousPid = Number(readJson(paths.pid))
        if (!child && previousPid && pidAlive(previousPid)) {
          state.pid = previousPid
          if (await health()) {
            state.version ??= readJson(paths.current)?.version
            state.phase = 'running'
            state.startedAt = Date.now()
            state.lastHealthyAt = Date.now()
            log(`adopted running proxy pid=${previousPid}`)
            scheduleHealthLoop()
            return
          }
          log(`previous proxy pid=${previousPid} is unhealthy; replacing it`)
          await killPid(previousPid)
          state.pid = undefined
        }

        const exe = await ensureBinary()
        state.exe = exe

        const resolved = await resolveEffectivePort(conf.port || 8317)
        state.effectivePort = resolved.port
        if (resolved.adopted) {
          state.version ??= readJson(paths.current)?.version
          state.phase = 'running'
          state.startedAt = Date.now()
          state.lastHealthyAt = Date.now()
          log(`adopted running proxy on port ${resolved.port} (no pid on record)`)
          scheduleHealthLoop()
          return
        }

        await ensureConfig(resolved.port)
        state.phase = 'starting'
        await spawnProxy(exe)
        state.startedAt = Date.now()
        const healthy = await waitHealthy()
        if (healthy) {
          state.phase = 'running'
          state.lastHealthyAt = Date.now()
          backoffMs = 1_000
          log(`running (v${state.version ?? '?'}, pid=${state.pid}, ${baseUrl()})`)
        } else if (child || pidAlive(state.pid)) {
          state.phase = 'starting'
          warn('proxy process is up but not yet answering the management API')
        } else {
          state.phase = 'error'
          state.error = 'CLIProxyAPI exited during startup; check cliproxy/logs/cliproxy.log'
        }
        scheduleHealthLoop()
      } catch (error) {
        state.phase = 'error'
        state.error = error instanceof Error ? error.message : String(error)
        warn(`start failed: ${state.error}`)
      }
    })().finally(() => {
      startPromise = undefined
    })
    return startPromise
  }

  async function stop() {
    stopping = true
    clearInterval(healthTimer)
    clearTimeout(restartTimer)
    healthTimer = undefined
    restartTimer = undefined
    const pid = child?.pid ?? state.pid
    child = undefined
    if (state.mode === 'managed' && pid) {
      await killPid(pid)
      rmSync(paths.pid, { force: true })
    }
    state.pid = undefined
    state.phase = 'stopped'
  }

  async function restart() {
    if (state.mode === 'external') {
      state.phase = (await health()) ? 'external-ok' : 'external-unreachable'
      return
    }
    const pid = child?.pid ?? state.pid
    stopping = true
    if (pid) await killPid(pid)
    child = undefined
    state.pid = undefined
    stopping = false
    await start()
  }

  function status() {
    const conf = settings()
    const configured = conf.mode === 'managed' || conf.mode === 'external' ? conf.mode : 'off'
    return {
      mode: state.phase === 'idle' || state.phase === 'off' ? configured : state.mode,
      phase: configured === 'off' && state.phase === 'idle' ? 'off' : state.phase,
      version: state.version,
      pid: state.pid,
      port: state.effectivePort,
      baseUrl: baseUrl(),
      error: state.error,
      startedAt: state.startedAt,
      lastHealthyAt: state.lastHealthyAt,
      home: paths.home,
    }
  }

  return { start, stop, restart, status, health, baseUrl, paths }
}
